#!/bin/bash

#################################################
# Zalkeen Network                               #
#-----------------------------------------------#
# Public file share                             #
# by Grim Kriegor (grimkriegor@krutt.org)       #
#################################################
# Last Revision: Feb 2017
#################################################

#Configuration
USER=grim
MACHINE=helbaster.zalkeen.us
PORT=2675
PREFIX="https://grimkriegor.zalkeen.us/public/" 
REMOTEPUBLIC="/home/$USER/Web/grimkriegor.zalkeen.us/public"

#URLENCODER="$HOME/.urlencode.sed"

#Check filename
if [ "$1" != "" ]; then
  FILE="$1"
else
  exit 0
fi

#Upload
echo "File is: $FILE"
echo "UPLOADING $FILE"
scp -q -P$PORT "$FILE" $USER@$MACHINE:$REMOTEPUBLIC
ssh -q -p$PORT $USER@$MACHINE chmod 755 \"$REMOTEPUBLIC/${FILE}\"

#Encode URL
echo "ENCODING $FILENAME"
FILENAME=$(basename "$FILE")
#FILENAMEENC=$(php -r "echo urlencode(\"$FILENAME\");")
#FILENAMEENC=$(echo $FILENAME | sed -f $URLENCODER)
FILENAMEENC=$(echo $FILENAME | sed -e 's/%/%25/g' -e 's/ /%20/g' -e 's/ /%09/g' -e 's/!/%21/g' -e 's/"/%22/g' -e 's/#/%23/g' -e 's/\$/%24/g' -e 's/\&/%26/g' -e 's/'\''/%27/g' -e 's/(/%28/g' -e 's/)/%29/g' -e 's/\*/%2a/g' -e 's/+/%2b/g' -e 's/,/%2c/g' -e 's/-/%2d/g' -e '#s/\./%2e/g' -e 's/\//%2f/g' -e 's/:/%3a/g' -e 's/;/%3b/g' -e 's//%3e/g' -e 's/?/%3f/g' -e 's/@/%40/g' -e 's/\[/%5b/g' -e 's/\\/%5c/g' -e 's/\]/%5d/g' -e 's/\^/%5e/g' -e 's/_/%5f/g' -e 's/`/%60/g' -e 's/{/%7b/g' -e 's/|/%7c/g' -e 's/}/%7d/g' -e 's/~/%7e/g' -e 's/      /%09/g')
echo $FILENAMEENC

#Send notifications and copy paste url
echo -n "$PREFIX$FILENAMEENC" 
echo -n "$PREFIX$FILENAMEENC" | xclip -selection clipboard
notify-send "Zalkeen Public Link" "$PREFIX$FILENAMEENC" 
